"""spikes/api/domain/migrations/0001_initial.py: Create spike domain tables.

Related modules: domain.models. Generated by Django 6.1 and header-annotated.
"""

# Generated by Django 6.1 on 2026-08-28 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('workspace_type', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='workspace_name_not_empty'), models.UniqueConstraint(fields=('workspace_type', 'name'), name='workspace_type_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='domain.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['workspace', 'status', 'created_at'], name='project_ws_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='project_name_not_empty'), models.UniqueConstraint(fields=('workspace', 'name'), name='project_workspace_name_unique')],
            },
        ),
    ]
