"""spikes/api/domain/migrations/0002_enum_value_constraints.py: Add enum checks.

Related modules: domain.models. Generated by Django 6.1 and header-annotated.
"""

# Generated by Django 6.1 on 2026-08-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='project_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('workspace_type__in', ['personal', 'organization'])), name='workspace_type_valid'),
        ),
    ]
